AccountApp/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from . import views

urlpatterns = [
    # post views
    url(r'^login/$',views.user_login,name='login'),
    url(r'^register/$',views.register,name='register'),
    url(r'^confrim/$',views.Confrim_check,name='Confrim_check'),
    url(r'^profile/$',views.profile,name='profile'),
    url(r'^logout/$', logout, name='logout'),
]

blog/urls.py
from django.urls import path
from . import views, api_view

# app_name = "blog"

urlpatterns = [
    path('', views.home_page, name='home'),
    path('hotel/<int:id>/', views.hotel_detail, name='hotel_detail'),
    path('hotel/<int:id>/reserve/', views.hotel_reserve, name='hotel_reserve'),
    path('hotel/search/', views.search, name="search"),
    path('hotel/reserve-factor/<str:tracking_code>/', views.reserve_factor, name='reserve_factor'),
    path('hotel/reservation-history/', views.reservation_history, name='reservation_history'),
    path('hotel/reservation-tracking/', views.reservation_tracking, name='reservation_tracking'),
    path('hotel/compare-hotel/', views.compare_hotel, name='compare_hotel'),
    path('hotel/api/reservation-tracking/',
        api_view.ReserveTrackingAPIView.as_view(),
        name='api_reservation_tracking')
]

hotel_reservation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace="blog")),
    path('accounts/',include(('AccountApp.urls', 'AccountApp'), namespace='AccountApp')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

AccountApp/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    phone = models.CharField(max_length=15,blank=False)
    national_id = models.CharField(max_length=10,blank=False)

    def __str__(self):
        return self.national_id

AccountApp/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):

    #phone Number:
    phone = forms.CharField(max_length=11, label='Phone number')

    #national ID:
    national_id = forms.CharField(label="National id")
    
    # password 
    password = forms.CharField(label='Password',widget=forms.PasswordInput)

    # confrim password
    password2 = forms.CharField(label='Repeat password',widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'].required = True

    class Meta:
        model = User

        fields = ('first_name','last_name','email','username')

    def clean_password2(self):
        cd = self.cleaned_data

        if (cd['password'] != cd['password2']):
            raise forms.ValidationError('Passwords do not match !')
            
        return cd['password2']


class ChangeProfileInfoForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.req_user = kwargs.pop('username', None)
        self.req_email = kwargs.pop('email', None)
        super(ChangeProfileInfoForm, self).__init__(*args, **kwargs)

    username = forms.CharField(label='نام کاربری', required=True)
    
    first_name = forms.CharField(label='نام')

    last_name = forms.CharField(label='نام خانوادگی')

    email = forms.EmailField(label='ایمیل', required=True)

    phone = forms.CharField(label='تلفن همراه', required=False)

    national_id = forms.CharField(label="کد ملی", required=False)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if self.req_user != username:
            if User.objects.filter(username=username).count():
                raise forms.ValidationError('این نام کاربری در دسترس نمی باشد.')

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if self.req_email != email:
            if email and User.objects.filter(email=email).count():
                raise forms.ValidationError('این ایمیل توسط حساب کاربری دیگری در حال استفاده است.')

        return email


class ChangePasswordForm(forms.Form):
    # password 
    password = forms.CharField(label='رمز عبور',widget=forms.PasswordInput)

    # confrim password
    password2 = forms.CharField(label='تکرار رمز عبور',widget=forms.PasswordInput)

    def clean_password2(self):
            cd = self.cleaned_data

            if (cd['password'] != cd['password2']):
                raise forms.ValidationError('رمز ها همخوانی ندارند.')
                
            return cd['password2']

AccountApp/views.py
import random
import string
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from django.core import serializers
from django.core.mail import send_mail
from django.contrib.auth import authenticate,login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sessions.middleware import SessionMiddleware
from django.urls import reverse
from .forms import LoginForm, UserRegistrationForm, ChangeProfileInfoForm, ChangePasswordForm
from .models import Profile


# Create your views here.


def user_login(request):
    error = ""
    if (request.method == 'POST'):
        form = LoginForm(request.POST)

        if (form.is_valid()):
            cd = form.cleaned_data

            user = authenticate(username = cd['username'],password = cd['password'])

            if (user is not None):
                if user.is_active:
                    login(request,user)

                    return HttpResponseRedirect(reverse('blog:home'))
                
                else:
                    error = "حساب کاربری شما غیر فعال است."
            else:
                error = "نام کاربری یا رمز عبور اشتباه است."
    else:
        form = LoginForm()
        
    return render(request,'AccountApp/login.html',{'form':form, 'error':error})


def register(request):

    global user_form
    global new_user

    if (request.method == 'POST'):
        user_form = UserRegistrationForm(request.POST)

        if user_form.is_valid():
            # create a new user
            new_user = user_form.save(commit=False)
            # set password:
            new_user.set_password(user_form.cleaned_data['password'])

            # create a password here
            GeneratedPass = PassGen()

            # send password to user email
            # email body
            Email_Body = 'Dear ' + user_form.cleaned_data['first_name']
            Email_Body += ' ' + user_form.cleaned_data['last_name']
            Email_Body += '\n\nYour Verification Code is '
            Email_Body += GeneratedPass

            # email subject 
            Email_Subject = 'Verify your account'
            
            # To :
            Email_reciver = [user_form.cleaned_data['email']]

            # main part of sending :
            send_mail(Email_Subject,Email_Body,settings.EMAIL_HOST_USER,Email_reciver,fail_silently=True)
            # open confrim page
            
            request.session['MainPass'] = GeneratedPass

            return render(request,'AccountApp/Confrim.html')
            
    else:
        user_form = UserRegistrationForm()
    
    return render(request,'AccountApp/register.html',{'user_form':user_form})


def PassGen():
    # create a random password 
    # lenght = 6
    # lower case , uppercase and numbers

    valid_Chars = string.ascii_lowercase
    valid_Chars += string.ascii_uppercase
    valid_Chars += '0123456789'

    GenPass = ''

    for i in range(6):
        GenPass += random.choice(valid_Chars)

    return GenPass

def Confrim_check(request):
    Confrim_Pass = request.POST.get('Confpass')
    MainPass = request.session.get('MainPass')
    
    if Confrim_Pass == MainPass:
        # create user

        global new_user
        global user_form
        new_user.save()
        national_id = user_form.cleaned_data['national_id']
        phone = user_form.cleaned_data['phone']

        Profile.objects.create(user=new_user,phone=phone,national_id=national_id)

        return HttpResponseRedirect(reverse('AccountApp:login'))
    else :
        return render(request,'AccountApp/Confrim.html',{'error':'کد تایید شما نادرست است.'})


@login_required
def profile(request):
    
    flag = 0
    user = request.user
    profile = get_object_or_404(Profile, user=user)

    if request.method == 'POST':
        ### if request came from form1
        if request.POST['form_select'] == 'form1':
            flag = 1
            ### send original username and email for validation in form
            info_form = ChangeProfileInfoForm(request.POST,
                                              username=user.username,
                                              email=user.email)
            if info_form.is_valid():

                user.username = info_form.cleaned_data['username']
                user.first_name = info_form.cleaned_data['first_name']
                user.last_name = info_form.cleaned_data['last_name']
                user.email = info_form.cleaned_data['email']
                profile.national_id = info_form.cleaned_data['national_id']
                profile.phone = info_form.cleaned_data['phone']

                user.save()
                profile.save()

        ### if request came from form2
        elif request.POST['form_select'] == 'form2':
            flag = 2
            pass_form = ChangePasswordForm(request.POST)
            if pass_form.is_valid():
                password = pass_form.cleaned_data["password"]
                user.set_password(password)
                user.save()
                if user.is_active:
                    login(request, user)

    if flag == 0 or flag == 2:
        profile_initial = {'username': user.username,
                           'first_name':user.first_name,
                           'last_name':user.last_name,
                           'email':user.email,
                           'national_id':profile.national_id,
                           'phone':profile.phone}
        info_form = ChangeProfileInfoForm(initial=profile_initial)
    
    if flag == 0 or flag == 1:
        pass_form = ChangePasswordForm()

    return render(request, 'AccountApp/profile.html', {
            'profile': profile,
            'info_form': info_form,
            'pass_form': pass_form,
        })

AccountApp/templates/AccountApp/Confrim.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="rtl">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
  </head>
  <body>
    <div class="login-box">
        <h1>تایید حساب</h1>
        <form action ="{% url 'AccountApp:Confrim_check' %}" method="post">
            {% csrf_token %}
            <div class="textbox">
                <i class="fas fa-lock"></i>
                <input type="text" name="Confpass" placeholder="کد تایید">
            </div>
            <h4>{{ error }}</h4>
            <input type="submit" class="btn" value="تایید">
            
            <h4>ایمیل خود را چک کنید و کد تایید فرستاده شده را وارد کنید.</h4>

        </form>
    </div>
  </body>
</html>

AccountApp/templates/AccountApp/login.html
{% load widget_tweaks %}
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en" dir="rtl">
  <head>
    <meta charset="utf-8">
    <title>ورود</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">

  </head>
  <body>
    {% include "header.html" %}
<div class="login-box">
  <h1>ورود</h1>
<form method="post" action=".">
    {% csrf_token %}

    {{ form.non_field_errors }}
    
    <div class="textbox">
        <i class="fas fa-user"></i>
        {% render_field form.username placeholder="نام کاربری" %}
        {{ form.username.errors }}
    </div>

    <div class="textbox">
        <i class="fas fa-lock"></i>
        {% render_field form.password placeholder="رمز عبور" %}
        {{ form.password.errors }}
    </div>
    <input type="submit" class="btn" value="ورود">
    <h3>{{ error }}</h3>

</form>
<p>حساب کاربری ندارید؟ <a style="color:white;" href="{% url 'AccountApp:register' %}">ثبت نام</a></p>
</div>
  </body>
</html>

AccountApp/templates/AccountApp/profile.html
{% load staticfiles %}

<!DOCTYPE html>
<html dir="rtl">
<head lang="en">
    <meta charset="UTF-8">
    <title>صفحه کاربری</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" type="text/css">
    <style type="text/css">
        .black-box{
            display: flex;
            flex-direction: row;
            /*justify-content: center;*/
            /*align-items: stretch;*/
            /*align-content: stretch;*/
            /*flex-wrap: wrap;*/
            font-family: Yekan;
            direction: rtl;
            color: white;
            background-color: rgba(0,0,0,0.5);
            border-radius: 3px;

            /*float: right;*/
            width:95%;
            box-shadow: 0 0 8px #006622; 
            margin-right: auto;
            margin-left: auto;
            padding:10px;
            margin-bottom: 5px;
        }
        .item{
            align-self: auto;
        }
    </style>
</head>
<body>
{% include "header.html" %}
<br><br>

<div class="black-box">

<!-- <div class="item"><h3>اطلاعات حساب کاربری:</h3></div> -->
<div class="item">
نام کاربری: {{profile.user.username}}<br>
نام: {{profile.user.first_name}}<br>
نام خانوادگی: {{profile.user.last_name}}<br>
ایمیل: {{profile.user.email}}<br>
شماره موبایل: {{profile.phone}}<br>
کد ملی: {{profile.national_id}}<br>
<a href="{%url 'blog:reservation_history'%}"><button>تاریخچه رزروها</button></a>
</div>
</div>
<!-- <br /> -->
    <div style="display: flex; flex-direction: row; justify-content: center;">

        <div class="testbox">
        <form method="post">
          <br/>
          <fieldset>
            <legend>تغییر رمز عبور</legend>
            <div class="colums">
                {% csrf_token %}
                {{pass_form.as_p}}
                <input type="hidden" value="form2" name="form_select">
            </div>
          </fieldset>
          <br/>
          <div class="btn-block">
            <button type="submit">ثبت تغییرات</button>
          </div>
        </form>
        </div>

        <div class="testbox">
        <form method="post">
          <br/>
          <fieldset>
            <legend>تغییر اطلاعات حساب کاربری</legend>
            <div class="colums">
                {% csrf_token %}
                {{info_form.as_p}}
                <input type="hidden" value="form1" name="form_select">
            </div>
          </fieldset>
          <br/>
          <div class="btn-block">
            <button type="submit">ثبت تغییرات</button>
          </div>
        </form>
        </div>

    </div>

  </body>
</html>

AccountApp/templates/AccountApp/register.html
{% load widget_tweaks %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="rtl">
  <head>
    <meta charset="utf-8">
    <title>ثبت نام</title>
    <link rel="stylesheet" href="{% static 'css/signup.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
  </head>

  <body>
    {% include "header.html" %}
    <br><br><br>

<div class="signup-box" style="margin-top: 180px;">
<h1> ثبت نام کاربر </h1>

<form method="post" action=".">
  {% csrf_token %}

  {{ form.non_field_errors }}

    <div class="textbox">
        <i class="fas fa-user"></i>
        {% render_field user_form.first_name placeholder="نام" %}
        {{ user_form.first_name.errors }}
    </div>

    <div class="textbox">
        <i class="fas fa-user"></i>
        {% render_field user_form.last_name placeholder="نام خانوادگی" %}
        {{ user_form.last_name.errors }}
    </div>

    <div class="textbox">
        <i class="fas fa-user"></i>
        {% render_field user_form.national_id placeholder="شماره ملی" %}
        {{ user_form.national_id.errors }}
    </div>

    <div class="textbox">
        <i class="fas fa-user"></i>
        {% render_field user_form.phone placeholder="شماره موبایل" %}
        {{ user_form.phone.errors }}
    </div>

    <div class="textbox">
        <i class="fas fa-user"></i>
        {% render_field user_form.email placeholder="ایمیل" %}
        {{ user_form.email.errors }}
    </div>

    <div class="textbox">
        <i class="fas fa-user"></i>
        {% render_field user_form.username placeholder="نام کاربری" %}
        {{ user_form.username.errors }}
    </div>

    <div class="textbox">
        <i class="fas fa-lock"></i>
        {% render_field user_form.password placeholder="رمز عبور" %}
        {{ user_form.password.errors }}
    </div>

    <div class="textbox">
        <i class="fas fa-lock"></i>
        {% render_field user_form.password2 placeholder="وارد کردن دوباره رمز عبور" %}
        {{ user_form.password2.errors }}
    </div>

    <input type="submit" class="btn" value="ثبت نام">

</form>

</div>
</body>
</html>

AccountApp/templates/AccountApp/register_done.html
{% extends "base.html" %}

{% block title %}
    Welcome
{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.firstname }} !</h1>
    <p>Your account has been seccessfully created! now you can <a href="{% url "login" %}">log in</a>.</p>
{% endblock %}