blog/urls.py
from django.urls import path
from . import views, api_view

# app_name = "blog"

urlpatterns = [
    path('', views.home_page, name='home'),
    path('hotel/<int:id>/', views.hotel_detail, name='hotel_detail'),
    path('hotel/<int:id>/reserve/', views.hotel_reserve, name='hotel_reserve'),
    path('hotel/search/', views.search, name="search"),
    path('hotel/reserve-factor/<str:tracking_code>/', views.reserve_factor, name='reserve_factor'),
    path('hotel/reservation-history/', views.reservation_history, name='reservation_history'),
    path('hotel/reservation-tracking/', views.reservation_tracking, name='reservation_tracking'),
    path('hotel/compare-hotel/', views.compare_hotel, name='compare_hotel'),
    path('hotel/api/reservation-tracking/',
        api_view.ReserveTrackingAPIView.as_view(),
        name='api_reservation_tracking')
]

hotel_reservation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace="blog")),
    path('accounts/',include(('AccountApp.urls', 'AccountApp'), namespace='AccountApp')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.conf import settings
from django.db.models.signals import post_save
import uuid


# Create your models here.
def track_code_generator():
    return str(uuid.uuid4())[:8]


def hotel_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/hotel_<name>/<filename>
    if instance.__class__.__name__ == 'Hotel':
        return 'hotel_{0}/{1}'.format(instance.name, filename)
    else:
        return 'hotel_{0}/{1}'.format(instance.hotel.name, filename)


class Hotel(models.Model):
    name = models.CharField(max_length=50)
    rating = models.SmallIntegerField()
    logo = models.ImageField(upload_to=hotel_directory_path, blank=True)
    address = models.TextField(max_length=255)
    description = models.TextField()
    phone = models.CharField(max_length=11)
    city = models.CharField(max_length=40)
    
    ordinary_rooms = models.IntegerField()
    ordinary_rooms_price = models.IntegerField()
    vip_rooms = models.IntegerField()
    vip_rooms_price = models.IntegerField()
    
    discount = models.IntegerField()

    def __str__(self):
        return  '{}'.format(self.name)

    def get_absolute_url(self):
        return reverse('blog:hotel_detail', args=[self.id])


def make_rooms(sender, **kwargs):
    if not Room.objects.filter(hotel=kwargs['instance']):
        ordinary_rooms          = kwargs['instance'].ordinary_rooms
        ordinary_rooms_price    = kwargs['instance'].ordinary_rooms_price
        vip_rooms               = kwargs['instance'].vip_rooms
        vip_rooms_price         = kwargs['instance'].vip_rooms_price

        for i in range(1, ordinary_rooms + vip_rooms + 1):
            if i<=ordinary_rooms:
                Room.objects.create(hotel=kwargs['instance'], room_number=i,
                                room_type='ordinary', price=ordinary_rooms_price)
            else:
                Room.objects.create(hotel=kwargs['instance'], room_number=i,
                                room_type='vip', price=vip_rooms_price)

post_save.connect(make_rooms, sender=Hotel)


class Room(models.Model):
    ROOM_TYPE_CHOICES = (
        ('vip', 'VIP'),
        ('ordinary', 'Ordinary'),
    )

    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_number = models.IntegerField()
    room_type = models.CharField(max_length=10, choices=ROOM_TYPE_CHOICES, default='ordinary')
    price = models.IntegerField()

    def __str__(self):
        return  'Room {}-{}'.format(self.hotel.name, self.room_number)


class Reserve(models.Model):
    STATUS_CHOICES = (
        ('open', 'Open'),
        ('closed', 'Closed'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ManyToManyField(Room)
    beginDate       = models.DateField()
    endDate         = models.DateField()
    totalPrice      = models.IntegerField()
    trackingCode    = models.CharField(max_length=10, unique=True, default=track_code_generator)
    created         = models.DateTimeField(auto_now_add=True)
    status          = models.CharField(max_length=10, choices=STATUS_CHOICES, default='open')

    def __str__(self):
        return  '{}'.format(self.trackingCode)


class HotelPicture(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE, related_name="hotel_pictures")
    picture = models.ImageField(upload_to=hotel_directory_path, null=False)

    def __str__(self):
        return  'Picture {}-{}'.format(self.hotel.name, self.id)


class Score(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    score = models.SmallIntegerField()
    description = models.TextField(max_length=300)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return  'Score {1}-{0}'.format(self.hotel.name, self.user.username)

blog/forms.py
from datetime import date
from django import forms
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget
from .models import Score


class HotelDatePickerForm(forms.Form):
    begin = JalaliDateField(label=('تاریخ ورود:'), widget=AdminJalaliDateWidget)
    end = JalaliDateField(label=('تاریخ خروج:'), widget=AdminJalaliDateWidget)

    def clean(self):
        cleaned_data = super(HotelDatePickerForm, self).clean()
        begin = cleaned_data.get('begin')
        end = cleaned_data.get('end')
        # Check if begin date is greater than today date
        if begin < date.today() or begin >= end:
            raise forms.ValidationError('تاریخ ها نامعتبر است.')


class ReservationTrackingForm(forms.Form):
    tracking_code = forms.CharField(max_length=10, label="کد پیگیری")
    phone = forms.CharField(max_length=11, label='شماره تلفن همراه')
    

class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ('score', 'description')
        widgets = {
                    'description': forms.Textarea(attrs={'class':'textarea-form', 'cols': 65, 'rows': 8}),
                    'score': forms.RadioSelect(choices=[(1,1),(2,2),(3,3),(4,4),(5,5)]),
                  }

blog/views.py
from datetime import date, timedelta, datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.conf import settings
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from jalali_date import datetime2jalali, date2jalali
from .models import Hotel, Room, Reserve, Score, HotelPicture
from .forms import HotelDatePickerForm, ReservationTrackingForm, ScoreForm


def home_page(request):
    hotel_suggestions = Hotel.objects.filter(rating__gt=3).order_by('-rating')
    hotel_suggestions = hotel_suggestions[:3]

    return render(request, 'blog/hotel/home.html',
                 {'hotel_suggestions': hotel_suggestions,
                 })


@require_http_methods(["POST", "GET"])
def hotel_detail(request, id):
    hotel = get_object_or_404(Hotel, id=id)
    pictures = HotelPicture.objects.filter(hotel=hotel)

    if request.method == "POST":
        if request.user.is_authenticated:  
            score_form = ScoreForm(request.POST)
            if score_form.is_valid():
                score = score_form.save(commit=False)
                score.user  = request.user
                score.hotel = hotel
                score.save()
        else:
            return HttpResponseRedirect(reverse('AccountApp:login'))
    else:
        score_form = ScoreForm()
        
    scores_list = Score.objects.filter(hotel=hotel).order_by('-created')[:3]

    return render(request, 'blog/hotel/hotel_detail.html',
                 {'hotel': hotel,
                  'score_form': score_form,
                  'scores_list': scores_list,
                  'pictures': pictures})


@login_required
def hotel_reserve(request, id):
    error_message = None
    if request.method == "POST":
        ### if request came from form1
        if request.POST['form_select'] == 'form1':
            form = HotelDatePickerForm(request.POST)
            if form.is_valid():
                begin = form.cleaned_data.get('begin')
                end = form.cleaned_data.get('end')
            else:
                begin = date.today()
                end = date.today() + timedelta(days=3)
                error_message = ''
        ### if request came from form2
        elif request.POST['form_select'] == 'form2':
            reserve, begin, end, error_message = make_reserve(request)
            if error_message == None:
                return HttpResponseRedirect(reverse('blog:reserve_factor', args=(reserve.trackingCode,)))
            else:
                form = HotelDatePickerForm(initial={'begin': begin, 'end':end})
    ### if GET request
    else:
        begin = date.today()
        end = date.today() + timedelta(days=3)
        form = HotelDatePickerForm(initial={'begin': begin, 'end':end})

    hotel = get_object_or_404(Hotel, id=id)
    ### if error is from form1 do not show available rooms
    avl_rooms = []
    if error_message != '':
        room_list = Room.objects.filter(hotel__id=id)
        avl_rooms = check_room(room_list, begin, end)

    return render(request, 'blog/hotel/reserve.html',
            {'hotel': hotel, 'rooms': avl_rooms,
             'error_message': error_message, 'form':form,
             'begin': begin, 'end': end})


def check_room(rl, begin, end):
    avl_rooms = []
    for i in rl:
        temp = i.reserve_set.filter(beginDate__lte=begin, endDate__gt=begin)
        if temp.first() == None:
            temp = i.reserve_set.filter(beginDate__gt=begin)
            temp = temp.filter(beginDate__lt=end)
            if temp.first() == None:
                avl_rooms.append(i)

    return avl_rooms


def make_reserve(request):
    reserve = None
    error_message = None

    selected_rooms = request.POST.getlist('selected_rooms')
    hotel_id = request.POST['hotel_id']

    ### make date objects
    begin = request.POST['begin']
    end = request.POST['end']
    begin_test = begin.split('-')
    begin = datetime(int(begin_test[0]), int(begin_test[1]), int(begin_test[2]))
    end_test = end.split('-')
    end = datetime(int(end_test[0]), int(end_test[1]), int(end_test[2]))


    if selected_rooms:
        room_list = Room.objects.filter(hotel__id=hotel_id)
        avl_rooms = check_room(room_list, begin, end)
        avl_rooms = [str(i.id) for i in avl_rooms]
        ### Check if selected rooms still available or not
        if all(elem in avl_rooms  for elem in selected_rooms):
            ### Create Reserve
            days = (end - begin).days

            total_price = 0
            room_list = []
            for room_id in selected_rooms:
                room = Room.objects.filter(id=room_id)[0]
                room_list.append(room)
                total_price += room.price
            
            total_price = total_price*days

            ### calculate discount
            hotel = get_object_or_404(Hotel, id=hotel_id)
            total_price = (total_price*(100 - hotel.discount))/100

            reserve = Reserve.objects.create(user=request.user, beginDate=begin,
                                             endDate=end, totalPrice=total_price)
            reserve.room.set(room_list)
            reserve.save()
        else:
            ### if selected rooms are not available
            error_message = "اتاق های انتخابی در دسترس نمیباشد."

    else:
        ### if no rooms were selected
        error_message = "اتاقی انتخاب نشده است."

    return reserve, begin, end, error_message


@login_required
def reserve_factor(request, tracking_code):
    reserve = get_object_or_404(Reserve, trackingCode=tracking_code)
    return render(request, 'blog/hotel/reserve_factor.html',
                 {'reserve': reserve})


"""
this view has two forms one for searching over hotel names
and another one for search hotels by their city.
"""
@require_http_methods(["GET"])
def search(request):
    show_all = False
    ### these variables will send to template as context
    hotel_list = []
    city_checked = []
    ranking_checked = []
    hotel_name = ''

    ### Which form is submitted
    ## form1 gets hotel's name
    form_select = request.GET.get('form_select')
    if form_select == 'form1':
        hotel_name = request.GET.get('hotel_name')
        ### check if there is a hotel_name or the form was empty
        if hotel_name:
            hotel_list = Hotel.objects.filter(name=hotel_name)
        else:
            ## if form is empty show all hotels
            show_all = True

    ## form2 gets selected citys and rankings
    elif form_select == 'form2':
        city_checked = request.GET.getlist('city_checked')
        ranking_checked = request.GET.getlist('ranking_checked')
        ### check if there is a checked city or the form was empty
        if city_checked:
            ### check if there is a checked ranking or not
            if not ranking_checked:
                ## for every selected cities get their hotels and add them to hotel_list
                for city in city_checked:
                    for hotel in Hotel.objects.filter(city=city):
                        hotel_list.append(hotel)
        
            else:
                ## for every selected cities get their hotels and add them to hotel_list
                for city in city_checked:
                    for hotel in Hotel.objects.filter(city=city, rating__in=ranking_checked):
                        hotel_list.append(hotel)
        else:
            ## if no city was selected show all hotels based on ranking
            if ranking_checked:
                hotel_list = Hotel.objects.filter(rating__in=ranking_checked)
            else:
                show_all = True

    else:
        ## if request is GET and we don't submit any forms then show all hotels
        show_all = True

    ### show all the hotels
    if show_all==True:
        hotel_list = Hotel.objects.all()

    ### pagination hotel_list
    paginator = Paginator(hotel_list, 4) # 4 posts in each page
    page = request.GET.get('page')
    if page == None:
        page = 1

    try:
        hotel_list = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        hotel_list = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        hotel_list = paginator.page(paginator.num_pages)

    ### Get all city names
    all_hotels = Hotel.objects.all()    
    city_list = []
    for hotel in all_hotels:
        city_list.append(hotel.city)
    city_list = list(dict.fromkeys(city_list))

    ### make url for checked cities
    city_checked_url = ""
    for i in city_checked:
        city_checked_url += "&city_checked=" + i

    ranking_checked_url = ""
    for i in ranking_checked:
        ranking_checked_url += "&ranking_checked=" + i

    return render(request, 'blog/hotel/search.html',
                {'hotel_list': hotel_list, 'city_list': city_list,
                 'city_checked_url': city_checked_url,
                 'ranking_checked_url': ranking_checked_url, 'hotel_name': hotel_name})


"""
In this view user can see his/her profile information and 
reservation history.
"""
@require_http_methods(["GET"])
def reservation_history(request):
    user = request.user
    reserve_list = Reserve.objects.filter(user=user)

    ### pagination reserve_list
    paginator = Paginator(reserve_list, 3) # 3 posts in each page
    page = request.GET.get('page')

    try:
        reserve_list = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer deliver the first page
        reserve_list = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        reserve_list = paginator.page(paginator.num_pages)

    return render(request, 'blog/hotel/reservation_history.html',

blog/templates/blog/hotel/compare_hotel.html
{% load jalali_tags%}
{% load staticfiles %}
{% load mytags %}


<!DOCTYPE html>
<html dir="rtl">
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>مقایسه هتل ها</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/compare_hotel.css' %}" type="text/css">
</head>
<body style="color: white;">
{% include "header.html" %}
<br><br>
<div class="black-box">

<h3>مقایسه هتل ها</h3>

<form method="post">
    {% csrf_token %}

    <label for="hotel1">مقایسه</label>
    <select name="hotel1" id="hotel1">
        <option selected disabled hidden style='display: none' value=''></option>
        {% for hotel in hotel_list %}
          <option value="{{hotel.id}}">{{hotel.name}}</option>
        {% endfor %}
    </select>

    <label for="hotel2">با</label>
    <select name="hotel2" id="hotel2">
        <option selected disabled hidden style='display: none' value=''></option>
        {% for hotel in hotel_list %}
          <option value="{{hotel.id}}">{{hotel.name}}</option>
        {% endfor %}
    </select>

    <input type="submit" value="مقایسه کن">
</form>

</div>

{% if hotel1 and hotel2 %}

<table class="table-fill">
<tbody>
<tr>
  <td class="column1"></td>
  <td class="text-right"><img class="hotel-img" src="{{pic1.picture.url}}"></td>
  <td class="text-right"><img class="hotel-img" src="{{pic2.picture.url}}"></td>
</tr>
<tr>
  <td class="column1">نام هتل</td>
  <td class="text-right hotel-name">
    <a href="{{ hotel1.get_absolute_url }}">هتل {{hotel1.name}}</a>
  </td>
  <td class="text-right hotel-name">
    <a href="{{ hotel2.get_absolute_url }}">هتل {{hotel2.name}}</a>
  </td>
</tr>
<tr>
  <td class="column1">درجه</td>
  <td class="text-right">
    {% for i in hotel1.rating|myrange %}
        <span class="fa fa-star checked"></span>
    {% endfor %}
  </td>
  <td class="text-right">
    {% for i in hotel2.rating|myrange %}
        <span class="fa fa-star checked"></span>
    {% endfor %}
  </td>
</tr>
<tr>
  <td class="column1">آدرس</td>
  <td class="text-right">{{hotel1.address}}</td>
  <td class="text-right">{{hotel2.address}}</td>
</tr>
<tr>
  <td class="column1">توضیحات</td>
  <td class="text-right">{{hotel1.description}}</td>
  <td class="text-right">{{hotel2.description}}</td>
</tr>
<tr>
  <td class="column1">شروع قیمت از (تومان)</td>
  <td class="text-right">{{hotel1.ordinary_rooms_price}}</td>
  <td class="text-right">{{hotel2.ordinary_rooms_price}}</td>
</tr>
<tr>
  <td class="column1">بیشترین قیمت (تومان)</td>
  <td class="text-right">{{hotel1.vip_rooms_price}}</td>
  <td class="text-right">{{hotel2.vip_rooms_price}}</td>
</tr>
<tr>
  <td class="column1">تخفیف (درصد)</td>
  <td class="text-right">{{hotel1.discount}}</td>
  <td class="text-right">{{hotel2.discount}}</td>
</tr>
</tbody>
</table>
{% endif %}

</body>
</html>

blog/templates/blog/hotel/detail.html
{% load staticfiles %}


<!DOCTYPE html>
<html dir="rtl">
<head lang="en">
    <meta charset="UTF-8">
    <title>هتل {{hotel.name}}</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}" type="text/css">

</head>
<body style="color: white;">
{% include "header.html" %}
<br><br><br>
<h2>هتل {{hotel.name}}</h2>

<p>
    درجه هتل : {{hotel.rating}}<br/>
    تلفن تماس: {{hotel.phone}}<br/>
    شهر: {{hotel.city}}<br/>
    آدرس: {{hotel.address}}<br/>
</p>

<a href="{% url 'blog:hotel_reserve' hotel.id %}"><input type="button" value="رزرو"></a>



<form method="post">
    {% csrf_token %}
    {{score_form.as_p}}
    <input type="submit" value="ارسال نظر">
</form>


<p>
    {% for item in scores_list %}
        {{item.score}}<br />
        {{item.description}}<br />
    {% endfor %}
</p>
</body>
</html>

blog/templates/blog/hotel/hotel_detail.html
{% load static %}
{% load mytags %}


<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>هتل {{hotel.name}}</title>
    <link rel="stylesheet" href="{% static 'css/hotel_detail.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/header.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body onload="showSlides(1);">
<script>
    var slideIndex = 1;
    // showSlides(slideIndex);

    function plusSlides(n) {
        showSlides(slideIndex += n);
    }

    function currentSlide(n) {
        showSlides(slideIndex = n);
    }

    function showSlides(n) {
        var i;
        var slides = document.getElementsByClassName("mySlides");
        var dots = document.getElementsByClassName("dot");
        if (n > slides.length) {slideIndex = 1}
        if (n < 1) {slideIndex = slides.length}
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        for (i = 0; i < dots.length; i++) {
            dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";
        dots[slideIndex-1].className += " active";
    }
</script>

{% include "header.html" %}
<br><br><br>
<div class="wrapper2 row2">

    <div class="top1">
        <table>
            <tr>
                <td>
                    <h2>
                        هتل {{hotel.name}}
                    </h2>

                </td>
                {%if hotel.logo %}
                <td rowspan="2">
                    <img  src="{{ hotel.logo.url }}">
                </td>
                {% endif %}
            </tr>
            <tr>
                <td >
                    {% for i in hotel.rating|hotelstar %}
                        {% if i == 1 %}
                            <span class="fa fa-star checked"></span>
                        {% else %}
                            <span class="fa fa-star"></span>
                        {% endif %}
                    {% endfor %}
                </td>
            </tr>
        </table>
    </div>
    <br><br>
    <div class="top2">
    <div class="ss-single-main-cih-price-container">
        <div class="ss-single-main-cih-off-label">
            <span class="ss-single-main-cih-offl-name">تخفیف</span>
            <span class="ss-single-main-cih-offl-no">%{{hotel.discount}}</span>
        </div>

        <div class="ss-single-main-cihp-price">
            <span class="ss-single-main-cihpp-old">{{hotel.ordinary_rooms_price}} تومان</span>
            <span class="ss-single-main-cihpp-no ss-red">
                {% cal_discount hotel.ordinary_rooms_price hotel.discount %} تومان
            </span>
        </div>
    </div>
    </div>

    <div class="mid1 clear">
      <p dir="rtl">
          آدرس هتل: {{hotel.address}}
      </p>
        <hr>
      <p dir="rtl">
          <img style="width:15px; height:15px;" src="{% static 'css/img/phone-icon.png' %}">
          تلفن تماس: <span style="color: #4caf50">{{hotel.phone}}</span> 
      </p>
        <br>
        <div class="inf" dir="rtl">
                     تعداد اتاق<br/>
                     {{hotel.ordinary_rooms|add:hotel.vip_rooms}}

        </div>
        <div class="mihanwp-box">
            <p dir="rtl">
                {{hotel.description}}
            </p>
        </div>
        <br>
        <a href="{% url 'blog:hotel_reserve' hotel.id %}"><input style="float: left;" class="button" type="submit" value="رزرو"></a>

    </div>
    <br>
    <div class="mid2 ">
        <div class="slideshow-container">
            {% for item in pictures %}
                <div class="mySlides fade">
                    <div class="numbertext">{{forloop.counter}} / {{pictures|length}}</div>
                    <img src="{{item.picture.url}}" style="width:100%">
                    <!-- <div class="text">لابی</div> -->
                </div>
            {% endfor %}
            <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>

        </div>
        <!-- <br> -->

        <div style="text-align:center; margin-top: 5px;">
            {% for i in pictures|length|myrange %}
                <span class="dot" onclick="currentSlide({{i|add:1}});"></span>
            {% endfor %}
        </div>
      </div>

    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br><br><br><br>
</div>
<br><br>
<div class="comments">
    <div class="textarea clear">
    <form method="POST">
    <div class="rating-box">
         <table>
             <tr>
                 <td>
        <div class="rating">
            {% for radio in score_form.score %}
                <input id="rating-{{forloop.revcounter}}" type="radio" name="score" value="{{forloop.revcounter}}"/>
                <label for="rating-{{forloop.revcounter}}">
                    <i class="fa fa-star"></i>
                </label>
            {% endfor %}
        </div> 
                 </td>
                 <td>
                     <h4 >به این هتل امتیاز دهید</h4>
                 </td>
             </tr>
         </table>
    </div>
    <br><br>
        {{ score_form.description }}

        <br>
        <input class="button" type="submit" value="ثبت نظر">
        {% csrf_token %}
    </form>
    </div>


    <div class="usercm">
        <h4 style="text-align: right; margin-right: 15px">نظر کاربران </h4>
        
        {% for comment in scores_list %}

            <div class="user">
                <p>کاربر:‌ {{comment.user.username}} امتیاز: {{comment.score}}</p>
                <p>{{comment.description}}</p>
            </div>

        {% endfor %}
        <br><br><br><br>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br>
</div>
<div class="wrapper3 row3">
    <footer id="footer" class="clear">
        <p class="fl_left">Copyright &copy; 2020 - All Rights Reserved </p>

        <p class="fl_right">designed by qazal</p>
    </footer>
</div>

</body>
</html>